apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: view-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: view
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
